package com.model.upb;
// Generated Feb 4, 2023, 10:10:23 PM by Hibernate Tools 4.3.6.Final

import java.math.BigInteger;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Client generated by hbm2java
 */
@Entity
@Table(name = "client", catalog = "appli_commerce")
public class Client implements java.io.Serializable {

	private Integer idclient;
	private String nomclient;
	private String prenomclient;
	private BigInteger numero;

	public Client() {
	}

	public Client(String nomclient, String prenomclient, BigInteger numero) {
		this.nomclient = nomclient;
		this.prenomclient = prenomclient;
		this.numero = numero;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "IDCLIENT", unique = true, nullable = false)
	public Integer getIdclient() {
		return this.idclient;
	}

	public void setIdclient(Integer idclient) {
		this.idclient = idclient;
	}

	@Column(name = "NOMCLIENT", length = 30)
	public String getNomclient() {
		return this.nomclient;
	}

	public void setNomclient(String nomclient) {
		this.nomclient = nomclient;
	}

	@Column(name = "PRENOMCLIENT", length = 30)
	public String getPrenomclient() {
		return this.prenomclient;
	}

	public void setPrenomclient(String prenomclient) {
		this.prenomclient = prenomclient;
	}

	@Column(name = "NUMERO", precision = 30, scale = 0)
	public BigInteger getNumero() {
		return this.numero;
	}

	public void setNumero(BigInteger numero) {
		this.numero = numero;
	}

}
