package com.model.upb;
// Generated Feb 4, 2023, 10:10:23 PM by Hibernate Tools 4.3.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Commande generated by hbm2java
 */
@Entity
@Table(name = "commande", catalog = "appli_commerce")
public class Commande implements java.io.Serializable {

	private CommandeId id;

	public Commande() {
	}

	public Commande(CommandeId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idclient", column = @Column(name = "IDCLIENT", nullable = false)),
			@AttributeOverride(name = "idproduit", column = @Column(name = "IDPRODUIT", nullable = false)) })
	public CommandeId getId() {
		return this.id;
	}

	public void setId(CommandeId id) {
		this.id = id;
	}

}
