package com.model.upb;
// Generated Feb 4, 2023, 10:10:23 PM by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CommandeId generated by hbm2java
 */
@Embeddable
public class CommandeId implements java.io.Serializable {

	private int idclient;
	private int idproduit;

	public CommandeId() {
	}

	public CommandeId(int idclient, int idproduit) {
		this.idclient = idclient;
		this.idproduit = idproduit;
	}

	@Column(name = "IDCLIENT", nullable = false)
	public int getIdclient() {
		return this.idclient;
	}

	public void setIdclient(int idclient) {
		this.idclient = idclient;
	}

	@Column(name = "IDPRODUIT", nullable = false)
	public int getIdproduit() {
		return this.idproduit;
	}

	public void setIdproduit(int idproduit) {
		this.idproduit = idproduit;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CommandeId))
			return false;
		CommandeId castOther = (CommandeId) other;

		return (this.getIdclient() == castOther.getIdclient()) && (this.getIdproduit() == castOther.getIdproduit());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdclient();
		result = 37 * result + this.getIdproduit();
		return result;
	}

}
