package com.model.upb;
// Generated Feb 4, 2023, 10:10:23 PM by Hibernate Tools 4.3.6.Final

import java.math.BigInteger;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Date generated by hbm2java
 */
@Entity
@Table(name = "date", catalog = "appli_commerce")
public class Date implements java.io.Serializable {

	private Integer iddate;
	private int idplanning;
	private Date libelledate;
	private BigInteger montant;

	public Date() {
	}

	public Date(int idplanning) {
		this.idplanning = idplanning;
	}

	public Date(int idplanning, Date libelledate, BigInteger montant) {
		this.idplanning = idplanning;
		this.libelledate = libelledate;
		this.montant = montant;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "IDDATE", unique = true, nullable = false)
	public Integer getIddate() {
		return this.iddate;
	}

	public void setIddate(Integer iddate) {
		this.iddate = iddate;
	}

	@Column(name = "IDPLANNING", nullable = false)
	public int getIdplanning() {
		return this.idplanning;
	}

	public void setIdplanning(int idplanning) {
		this.idplanning = idplanning;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LIBELLEDATE", length = 10)
	public Date getLibelledate() {
		return this.libelledate;
	}

	public void setLibelledate(Date libelledate) {
		this.libelledate = libelledate;
	}

	@Column(name = "MONTANT", precision = 60, scale = 0)
	public BigInteger getMontant() {
		return this.montant;
	}

	public void setMontant(BigInteger montant) {
		this.montant = montant;
	}

}
