package com.model.upb;
// Generated Feb 4, 2023, 10:10:23 PM by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Planning generated by hbm2java
 */
@Entity
@Table(name = "planning", catalog = "appli_commerce")
public class Planning implements java.io.Serializable {

	private Integer idplanning;
	private int idclient;

	public Planning() {
	}

	public Planning(int idclient) {
		this.idclient = idclient;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "IDPLANNING", unique = true, nullable = false)
	public Integer getIdplanning() {
		return this.idplanning;
	}

	public void setIdplanning(Integer idplanning) {
		this.idplanning = idplanning;
	}

	@Column(name = "IDCLIENT", nullable = false)
	public int getIdclient() {
		return this.idclient;
	}

	public void setIdclient(int idclient) {
		this.idclient = idclient;
	}

}
