package com.model.upb;
// Generated Feb 4, 2023, 10:10:23 PM by Hibernate Tools 4.3.6.Final

import java.math.BigInteger;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Produits generated by hbm2java
 */
@Entity
@Table(name = "produits", catalog = "appli_commerce")
public class Produits implements java.io.Serializable {

	private Integer idproduit;
	private String nomproduit;
	private BigInteger prixproduit;
	private String descproduit;

	public Produits() {
	}

	public Produits(String nomproduit, BigInteger prixproduit, String descproduit) {
		this.nomproduit = nomproduit;
		this.prixproduit = prixproduit;
		this.descproduit = descproduit;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "IDPRODUIT", unique = true, nullable = false)
	public Integer getIdproduit() {
		return this.idproduit;
	}

	public void setIdproduit(Integer idproduit) {
		this.idproduit = idproduit;
	}

	@Column(name = "NOMPRODUIT", length = 20)
	public String getNomproduit() {
		return this.nomproduit;
	}

	public void setNomproduit(String nomproduit) {
		this.nomproduit = nomproduit;
	}

	@Column(name = "PRIXPRODUIT", precision = 20, scale = 0)
	public BigInteger getPrixproduit() {
		return this.prixproduit;
	}

	public void setPrixproduit(BigInteger prixproduit) {
		this.prixproduit = prixproduit;
	}

	@Column(name = "DESCPRODUIT", length = 50)
	public String getDescproduit() {
		return this.descproduit;
	}

	public void setDescproduit(String descproduit) {
		this.descproduit = descproduit;
	}

}
