package com.model.upb;
// Generated Feb 4, 2023, 10:10:23 PM by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Vendeur generated by hbm2java
 */
@Entity
@Table(name = "vendeur", catalog = "appli_commerce")
public class Vendeur implements java.io.Serializable {

	private Integer idvendeur;
	private int idplanning;
	private int idproduit;
	private String nomvendeur;
	private String prenomvendeur;
	private String nommagasin;
	private String motdepassevendeur;

	public Vendeur() {
	}

	public Vendeur(int idplanning, int idproduit) {
		this.idplanning = idplanning;
		this.idproduit = idproduit;
	}

	public Vendeur(int idplanning, int idproduit, String nomvendeur, String prenomvendeur, String nommagasin,
			String motdepassevendeur) {
		this.idplanning = idplanning;
		this.idproduit = idproduit;
		this.nomvendeur = nomvendeur;
		this.prenomvendeur = prenomvendeur;
		this.nommagasin = nommagasin;
		this.motdepassevendeur = motdepassevendeur;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "IDVENDEUR", unique = true, nullable = false)
	public Integer getIdvendeur() {
		return this.idvendeur;
	}

	public void setIdvendeur(Integer idvendeur) {
		this.idvendeur = idvendeur;
	}

	@Column(name = "IDPLANNING", nullable = false)
	public int getIdplanning() {
		return this.idplanning;
	}

	public void setIdplanning(int idplanning) {
		this.idplanning = idplanning;
	}

	@Column(name = "IDPRODUIT", nullable = false)
	public int getIdproduit() {
		return this.idproduit;
	}

	public void setIdproduit(int idproduit) {
		this.idproduit = idproduit;
	}

	@Column(name = "NOMVENDEUR", length = 30)
	public String getNomvendeur() {
		return this.nomvendeur;
	}

	public void setNomvendeur(String nomvendeur) {
		this.nomvendeur = nomvendeur;
	}

	@Column(name = "PRENOMVENDEUR", length = 30)
	public String getPrenomvendeur() {
		return this.prenomvendeur;
	}

	public void setPrenomvendeur(String prenomvendeur) {
		this.prenomvendeur = prenomvendeur;
	}

	@Column(name = "NOMMAGASIN", length = 30)
	public String getNommagasin() {
		return this.nommagasin;
	}

	public void setNommagasin(String nommagasin) {
		this.nommagasin = nommagasin;
	}

	@Column(name = "MOTDEPASSEVENDEUR")
	public String getMotdepassevendeur() {
		return this.motdepassevendeur;
	}

	public void setMotdepassevendeur(String motdepassevendeur) {
		this.motdepassevendeur = motdepassevendeur;
	}

}
